name: Server Build and Push Docker Image

on:
  push:
    branches:
      - main # Trigger only on pushes to main
  workflow_dispatch: # Allow manual runs if needed
      inputs:
        version:
          description: 'Version to build'
          required: true
          default: 'latest'


jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -f server-berea/Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/server-berea:${{ github.event.inputs.version }} server-berea/
        docker tag ${{ secrets.DOCKER_USERNAME }}/server-berea:${{ github.event.inputs.version }} ${{ secrets.DOCKER_USERNAME }}/server-berea:latest
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/server-berea:${{ github.event.inputs.version }}
        docker push ${{ secrets.DOCKER_USERNAME }}/server-berea:latest
